INSERT INTO dev.SFMC_BRIEF_PROD_CAT_TAXONOMY_CORRECTIONS(campaign_name, product_cat) VALUES 
('SAL002_BINGE_3mth_offer_Sex_and_the_City_Feb_2022', 'Binge'),
('SAL002_BINGE3mthoffer_TheStaircaseMay2022_SVOD', 'Binge'),
('SAL002_BINGE_3mth_HarryPotter_Jan2022', 'Binge'),
('SAL002_BINGE_3mth_LOVEME_Dec2021', 'Binge'),
('SAL007_FLIP&FOLDXSELL_SAMSUNG', 'Postpaid Mobile Handheld'),
('SAL002_Cross_Sell_FixedBlast_EDM', 'Fixed'),
('SAL002_BINGE_3mth_SATC_Dec2021', 'Binge'),
('SAL002_XsellApple13_CON_EDM_Pre-Order', 'Postpaid Mobile Handheld'), 
('SAL007_UpgradeApple13_CON_EDM_pre-order', 'Postpaid Mobile Handheld'),
('SAL007_UpgradeApple13_CON_EDM_Launch', 'Postpaid Mobile Handheld'),
('SAL002_XsellPixel6_CON_EDM_Launch', 'Postpaid Mobile Handheld'),
('SAL002_XsellApple13_CON_EDM_Launch', 'Postpaid Mobile Handheld'),
('SAL002_XsellPixel6_CON_EDM_pre-order', 'Postpaid Mobile Handheld'),
('SAL007_TCAppleTradeIn_IOs', 'Postpaid Mobile Handheld'),
('SAL007_UpgradeApple13_CON_EDM_Launch_resend', 'Postpaid Mobile Handheld'),
('SAL002_Xbox_GamePassUltimate_launch_2021_eDM', 'Xbox Game Pass Ultimate'),
('SAL007_UpgradeApple13_CON_SMS_Launch_resend', 'Postpaid Mobile Handheld'),
('SAL002_Kayo_15for12_BBL_Dec21', 'Kayo'),
('SAL002_XsellApple13_CON_SMS_Pre-Order', 'Postpaid Mobile Handheld'),
('SAL002_XsellApple13_CON_SMS_Launch', 'Postpaid Mobile Handheld'),
('STR003_NBNFlashSale_Dec21_FixedBase', 'Fixed'),
('SAL002_FY22_Kayo_T20WorldCup_SMS', 'Kayo'),
('SAL007_5GDecemberHols_PPM', 'Postpaid Mobile Handheld'),
('SAL002_NBNFlashSale_Oct21_FixedBase', 'Fixed'),
('SAL007_Upgrade_Pixel_CON_EDM', 'Postpaid Mobile Handheld'),
('STR003_NBNFlashSale_Oct21_FixedBase', 'Fixed'),
('STR003_MDUCA_NBN', 'Fixed'),
('SAL002_5GHome_XSell', 'Fixed'),
('SAL002_XsellPixel6_CON_SMS_Launch', 'Postpaid Mobile Handheld'),
('SAL002_XsellPixel6_CON_SMS_pre-order', 'Postpaid Mobile Handheld'),
('SAL007_LEGACY_CHURN_SMS_ANDROID_PPM', 'Postpaid Mobile Handheld'),
('SAL007_Upgrade_Pixel_CON_SMS', 'Postpaid Mobile Handheld'),
('SAL002_Xbox_GamePassUltimate_launch_2021_SMS', 'Xbox Game Pass Ultimate'),
('STR003_HFCUnPause_NBN', 'Fixed'),
('STR003_NBNMandatoryConnect90D_NBN', 'Fixed'),
('SAL002_HFC_restart_Breakglass', 'Fixed'),
('SAL002_HFC_Restart_eDMandSMS', 'Fixed'),
('SAL007_LEGACY_CHURN_SMS_IOS_PPM', 'Postpaid Mobile Handheld'),
('STR003_ModemReplacement', 'Fixed'),
('STR003_FireAndLift_NBN', 'Fixed'),
('SAL007_UpgradeApple13_CON_SMS_pre-order', 'Postpaid Mobile Handheld'),
('SAL007_UpgradeApple13_CON_SMS_Launch', 'Postpaid Mobile Handheld'),
('STR001_TCSwapOTMService_PPM', 'Postpaid Mobile Handheld'),
('STR013_InitialOffer_Airwave', 'Fixed'),
('SAL002_BPlusCSSAFixed_FY22Q3', 'Fixed'),
('SAL002_BPlusCSSAFixed_FY22Q1_2', 'Fixed'),
('SAL007_JBIFI59SMS', 'Postpaid Mobile Handheld'),
('SAL002_Cross_Sell_FixedBlast', 'Fixed'),
('STR003_LTNS_NBN', 'Fixed'),
('STR003_NBNMandatoryConnect38D_NBN', 'Fixed'),
('STR003_NBNMandatoryConnect60D_NBN', 'Fixed'),
('SAL007_UpgradeAppleBG13CON', 'Postpaid Mobile Handheld'),
('STR003_RFS012_NBN', 'Fixed'),
('SAL002_EOIApple13_EDM_pre-order', 'Postpaid Mobile Handheld'),
('SAL002_AppleDeviceLaunch_EOIDataCapture', 'Postpaid Mobile Handheld'),
('SAL002_XSell_HFC_Restart_SMS', 'Fixed'),
('STR003_IncompatibleModem', 'Fixed'),
('STR003_NBN53D_NBN', 'Fixed'),
('SAL002_XSell_HFC_Restart_Q1Offer', 'Fixed'),
('SAL007_SFXLPromo_MHH_Con', 'Postpaid Mobile Handheld'),
('SAL002_HFC_restart_100Welcome', 'Fixed'),
('STR001_TCSwapService_PPM', 'Postpaid Mobile Handheld'),
('STR003_NBN23DVoice_NBN', 'Fixed'),
('STR003_NBN23DBundle_NBN', 'Fixed'),
('STR003_NBN23DInternet_NBN', 'Fixed'),
('SAL003_CyberSS_newsletter_eDM', 'Cyber Security Device Protect'),
('STR003_NBNMandatoryConnect100D_SMS', 'Fixed'),
('SAL001_NoExcessData_Con_MBB_PostpaidMobileHandheld', 'Postpaid Mobile Broadband'),
('SAL002_EOIApple13_EDM_TRRpre-order', 'Postpaid Mobile Handheld'),
('STR003_NBN23DSC0_NBN', 'Fixed'),
('STR003_FlashSale_NBN', 'Fixed'),
('SAL007_TCSamsungTradeIn_Android', 'Postpaid Mobile Handheld'),
('SAL002_GoogleDeviceLaunch_EOIDataCapture', 'Postpaid Mobile Handheld'),
('SAL001_Xsell_Strategic Xsell_TC', 'Postpaid Mobile Handheld'),
('SAL002_FY22_Q3_SmartModem3_Launch_Switch_AO', 'Smart Modem'),
('SAL002_Kayo_AFL_Launch_eDMSMS', 'Kayo'),
('STR003_ContactValidation', 'Fixed'),
('STR002_TelstraInitiatedMigration_PPM', 'Postpaid Mobile Handheld'),
('STR003_Wifi_Issue_Proactive', 'Fixed'),
('SAL001_FY22_Q3_Disney_12mthsOffer_10daysReminder', 'Disney+'),
('SAL001_Fixed_Disney_plus', 'Disney+'),
('SAL002_Kayo_NRL_Launch_eDMSMS', 'Kayo'),
('STR003_5DDisconnection_NBN', 'Fixed'),
('STR003_NBNMandatoryConnect_DD', 'Fixed'),
('SAL007_XLCreditExp_PPM', 'Postpaid Mobile Handheld'),
('STR003_SuspensionSMS_NBN', 'Fixed'),
('SAL007_JBIFI69SMS', 'Postpaid Mobile Handheld'),
('STR003_NBNFlashSale_Feb22_FixedBase', 'Fixed'),
('SAL007_End_of_Postpaid_Device_Contract_PUSH', 'Postpaid Mobile Handheld'),
('STR003_NBNMandatoryConnectDD_NBN', 'Fixed'),
('STR002_RelianceOptOut_FixedWireless', 'Fixed'),
('STR003_NBNMandatoryConnect_NBN', 'Fixed'),
('SAL001_NoExcessData_Con_MBB', 'Postpaid Mobile Broadband'),
('SAL007_JBHIF99SMS', 'Postpaid Mobile Handheld'),
('SAL001_NoExcessData_Con_PPM', 'Postpaid Mobile Handheld'),
('STR003_NBNMandatoryConnect100D_NBN', 'Fixed'),
('STR003_35DDisconnectionOtm_NBN', 'Fixed'),
('STR003_DDBusinessVoice_NBN', 'Fixed'),
('STR003_nbnmigration_COATtactical', 'Fixed'),
('STR003_DDBusinessBundles_NBN', 'Fixed'),
('STR003_DDBusinessInternet_NBN', 'Fixed'),
('STR003_DDBusinessSC0_NBN', 'Fixed'),
('STR003_NBN_Fibre_Connect_A1_SRV', 'Fixed');
